trigger:
  platform: state
  entity_id: vacuum.xiaomi_vacuum_cleaner
  from: docked
  to: cleaning
action:
  service: notify.all_iphones
  data:
    title: "Robot"
    message: "Robot started to clean!"