- platform: template
  sensors:
    washing_machine:
      friendly_name: Washing machine
      value_template: >
        {{ states("sensor.washing_machine_watts") | float(0) > 3 }}
      delay_off: "00:05:00"
      icon_template: >
        {% if is_state("binary_sensor.washing_machine", "on") %}
          mdi:washing-machine
        {% else %}
          mdi:washing-machine-off
        {% endif %}
    worked_enough_today:
      friendly_name: Worked enough today
      value_template: >
        {{ states("sensor.time_at_work_today") | float(0) > 8 }}
      icon_template: mdi:work

    someone_showering:
      friendly_name: Someone is showering
      value_template: >
        {% set humidity = states("sensor.humidity_bathroom") | float(0) %}
        {% set treshold = 1.05 * state_attr("sensor.humidity_bathroom_stats", "median") | float(0) %}
        {% set derivative = states("sensor.humidity_bathroom_derivative") | float(0) %}
        {{ humidity > treshold and derivative > 0.25 }}

    motion_detected:
      friendly_name: Any motion detected
      value_template: >
        {{ is_state("binary_sensor.activity_in_bathroom", "on")
          or is_state("binary_sensor.activity_in_bedroom", "on")
          or is_state("binary_sensor.activity_in_livingroom", "on")
        or is_state("binary_sensor.motion_sensor_sportroom", "on")}}

    motion_detected_in_last_hour:
      friendly_name: Any motion detected in last hour
      value_template: >
        {{ is_state("binary_sensor.motion_detected", "on") }}
      delay_off: "01:00:00"

    someone_in_the_house_in_last_hour:
      friendly_name: Someone in the house in the last hour
      value_template: >
        {{ is_state("binary_sensor.motion_detected_in_last_hour", "on")
            or is_state("group.persons", "home") }}

    activity_in_bathroom:
      friendly_name: Activity in the bathroom
      value_template: >
        {{ is_state("binary_sensor.someone_showering", "on") }}
      delay_off: "00:03:00"

    activity_in_bedroom:
        friendly_name: Activity in the bedroom
        value_template: >
          {{ is_state("binary_sensor.motion_sensor_bedroom", "on") }}
        delay_off: "00:06:00"

    activity_in_sportroom:
      friendly_name: Activity in the sportroom
      value_template: >
        {{ is_state("binary_sensor.motion_sensor_sportroom", "on") }}
      delay_off: "00:20:00"

    activity_in_livingroom:
      friendly_name: Activity in the livingroom
      value_template: >
        {{ is_state("binary_sensor.motion_sensor_livingroom", "on") or
         is_state("media_player.sony_bravia_tv", "on") }}
      delay_off: "00:15:00"

    any_light_on:
      friendly_name: Any light is on
      value_template: >
        {% set schlafzimmerbeleuchtung_on = is_state("light.schlafzimmerbeleuchtung", "on") %}
        {% set wohnzimmerbeleuchtung_on = is_state("light.wohnzimmerbeleuchtung", "on") %}
        {% set sportzimmerbeleuchtung_on = is_state("light.sportzimmerbeleuchtung", "on") %}
        {% set schlafzimmerbeleuchtung_on = is_state("light.schlafzimmerbeleuchtung", "on") %}
        {{ schlafzimmerbeleuchtung_on or wohnzimmerbeleuchtung_on or sportzimmerbeleuchtung_on or schlafzimmerbeleuchtung_on }}

    anything_on:
      friendly_name: Anything is on
      value_template: >
        {% set light_on = is_state("binary_sensor.any_light_on", "on") %}
        {% set tv_on = is_state("media_player.sony_bravia_tv", "on") %}
        {% set sonos_schlafzimmer_on = is_state("media_player.schlafzimmer", "on") %}
        {% set sonos_living_room_on = is_state("media_player.living_room", "on") %}
        {% set sonos_living_room_2_on = is_state("media_player.living_room_2", "on") %}
        {{ light_on or tv_on or sonos_schlafzimmer_on or sonos_living_room_on or sonos_living_room_on_2 }}

    no_one_home:
      friendly_name: No one is home
      value_template: >
        {{ not is_state("person.benjamin", "home")
            and not is_state("person.jana", "home") }}

- platform: workday
  country: DE

- platform: trend
  sensors:
    humidity_bathroom_trend:
      entity_id: sensor.humidity_bathroom
      sample_duration: 300
      max_samples: 3
