- platform: group
  name: Küchenbeleuchtung
  entities:
    - light.hue_filament_bulb_1
    - light.hue_filament_bulb_2
    - light.hue_filament_bulb_3
    - light.hue_filament_bulb_4
- platform: group
  name: Wohnzimmerbeleuchtung
  entities:
    - light.hue_filament_bulb_5
    - light.hue_white_lamp_1
    - light.hue_go_1
- platform: group
  name: Sportzimmerbeleuchtung
  entities:
    - light.hue_color_spot_1
    - light.hue_color_spot_2
    - light.hue_color_spot_3
    - light.color_temperature_light_16
- platform: switch
  name: SchlafzimmerLichterkette
  entity_id: switch.configuration_tool_1
- platform: group
  name: Schlafzimmerbeleuchtung
  entities:
    - light.hue_ambiance_candle_1
    - light.schlafzimmerlichterkette