- platform: template
  switches:
    xiaomi_air_purifier_3h_led:
      friendly_name: "Display"
      value_template: "{{ is_state_attr('fan.xiaomi_air_purifier_3h', 'led', true) }}"
      turn_on:
        service: xiaomi_miio.fan_set_led_on
        data:
          entity_id: fan.xiaomi_air_purifier_3h
      turn_off:
        service: xiaomi_miio.fan_set_led_off
        data:
          entity_id: fan.xiaomi_air_purifier_3h
      icon_template: mdi:lightbulb-outline
    xiaomi_air_purifier_3h_child_lock:
      friendly_name: "Child lock"
      value_template: "{{ is_state_attr('fan.xiaomi_air_purifier_3h', 'child_lock', true) }}"
      turn_on:
        service: xiaomi_miio.fan_set_child_lock_on
        data:
          entity_id: fan.xiaomi_air_purifier_3h
      turn_off:
        service: xiaomi_miio.fan_set_child_lock_off
        data:
          entity_id: fan.xiaomi_air_purifier_3h
      icon_template: "mdi:lock-outline"
    xiaomi_air_purifier_3h_buzzer:
      friendly_name: "Buzzer"
      value_template: "{{ is_state_attr('fan.xiaomi_air_purifier_3h', 'buzzer', true) }}"
      turn_on:
        service: xiaomi_miio.fan_set_buzzer_on
        data:
          entity_id: fan.xiaomi_air_purifier_3h
      turn_off:
        service: xiaomi_miio.fan_set_buzzer_off
        data:
          entity_id: fan.xiaomi_air_purifier_3h
      icon_template: "mdi:volume-high"